xray_install_dir: /usr/local/etc/xray
xray_config_path: /usr/local/etc/xray/config.json
xray_log_dir: /var/log/xray
xray_error_log: /var/log/xray/error.log

xray_vless_port: 443
xray_vless_flow: xtls-rprx-vision

# Для REALITY лучше указывать реальный внешний TLS 1.3 / H2 сайт
xray_reality_server_name: www.microsoft.com
xray_reality_dest: "{{ xray_reality_server_name }}:443"
xray_reality_short_ids:
  - a1b2c3d4e5f60708

# Клиентские параметры
xray_client_fingerprint: chrome
xray_client_spider_x: /

# Firewall
xray_manage_firewall: true
xray_ssh_port: 22

# Если нужен UFW только на Debian-family
xray_enable_ufw: true

# Путь, куда локально будет рендериться клиентский профиль
xray_local_output_dir: ./artifacts

# Адрес сервера для клиента
xray_client_server: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
